{% set name = "zfit-physics" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zfit/zfit-physics/archive/{{ version }}.tar.gz
  sha256: dbdcbea5bc31fbfaae8630a2f8ff09c54e830e092c4a6f97a0657aac2ec6bde1

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }},<3.13
    - numpy
    - zfit >=0.23.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - zfit_physics
    - zfit_physics.models
    - zfit_physics.unstable

about:
  home: https://github.com/zfit/zfit-physics
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Physics extension to zfit
  dev_url: https://github.com/zfit/zfit-physics

extra:
  recipe-maintainers:
    - ikrommyd
    - chrisburr
    - jonas-eschle
