schema_version: 1

context:
  name: zfit-physics
  version: 0.9.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/zfit/zfit-physics/archive/${{ version }}.tar.gz
  sha256: 7e28626538fa27b2c6321854b67a40692bb472a41468a4d36b04f1e662ae1a3e

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }},<3.13
    - numpy
    - zfit >=0.23.0

tests:
  - python:
      imports:
        - zfit_physics
        - zfit_physics.models
        - zfit_physics.unstable
      pip_check: false
      python_version: ${{ python_min }}.*
about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Physics extension to zfit
  homepage: https://github.com/zfit/zfit-physics
  repository: https://github.com/zfit/zfit-physics

extra:
  recipe-maintainers:
    - ikrommyd
    - chrisburr
    - jonas-eschle
